# .slather.yml

coverage_service: cobertura_xml
xcodeproj: Example/AlamofireSessionRenewer.xcodeproj
scheme: AlamofireSessionRenewer-Example
configuration: TestedConfiguration
source_directory: AlamofireSessionRenewer/Classes
output_directory: path/to/xml_report
ignore:
  - Example/*
