osx_image: xcode10.1
language: 
- swift
script:
- xcodebuild test -enableCodeCoverage YES -workspace Example/AlamofireSessionRenewer.xcworkspace -scheme AlamofireSessionRenewer-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO
after_success:
- bash <(curl -s https://codecov.io/bash)