osx_image: xcode10.1
language: 
- swift
script:
- xcodebuild test -enableCodeCoverage YES -workspace Example/AlamofireSessionRenewer.xcworkspace -scheme AlamofireSessionRenewer-Example -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6s,OS=12.2'
after_success:
- bash <(curl -s https://codecov.io/bash)