name: CI
on:
  push:
    branches:
    - master
     
jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Publish to CocoaPod register
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: |
        echo Updating podspec.
        pod trunk push AlamofireSessionRenewer.podspec
